// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV2c6kLFIkJWdgV54mj3pIiuhFS_ptz-g',
    appId: '1:825334258321:web:2b2f5cc929318d65b87d30',
    messagingSenderId: '825334258321',
    projectId: 'watch-world-783ef',
    authDomain: 'watch-world-783ef.firebaseapp.com',
    storageBucket: 'watch-world-783ef.appspot.com',
    measurementId: 'G-Y15G3QF526',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVtboyV3HcaQfsGOT5cnekpr-Q0XY1Swk',
    appId: '1:825334258321:android:a311cbdeacd356ceb87d30',
    messagingSenderId: '825334258321',
    projectId: 'watch-world-783ef',
    storageBucket: 'watch-world-783ef.appspot.com',
  );
}
